services:
  recon-app:
    build: .
    container_name: recon_system
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: ["python", "app/main.py"]

  streamlit-ui:
    build: .
    container_name: streamlit_recon_ui
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    command: ["streamlit", "run", "ui/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
